stages:
  - build
  - staticAnalysis
  - test

# Frontend
frontend:
  image: node:14-alpine
  stage: build
  script:
    - cd alpha-built-frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - alpha-built-frontend/dist/

# Backend

build-alpha-built-backend:
  image: gradle:7.6.1-jdk17
  stage: build
  script:
    - cd alpha-built-backend
    - gradle assemble testClasses

checkStyle-alpha-built-backend:
  image: gradle:7.6.1-jdk17
  stage: staticAnalysis
  script:
    - cd alpha-built-backend
    - gradle checkstyleMain checkStyleTest
  allow_failure: false

test-alpha-built-backend:
  image: gradle:7.6.1-jdk17
  stage: test
  script:
    - cd alpha-built-backend
    - gradle test jacocoTestReport
    - if [ -e "build/reports/jacoco/test/html/index.html" ]; then cat build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%"; else echo "No test report."; fi
  coverage: /([0-9]{1,3})%/

